name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-python:
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: ${{ matrix.python }}

      - id: run
        name: Run
        run: pipenv run pytest
